name: GitLab

on:
  push:
    branches: [ master ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - env:
        GITLAB_USER: ${{ secrets.GITLAB_USER }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      run: |
        git remote add mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.in.htwg-konstanz.de/lehre/meiglspe/sose20/wete/projects/termin123
        git push mirror

