name: Laravel

on:
  push:
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: 12-alpine
        postgresql db: appointer
        postgresql user: appointer
        postgresql password: appointer
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: psql
        DB_DATABASE: appointer
        DB_USERNAME: appointer
        DB_PASSWORD: appointer
      run: vendor/bin/phpunit
